name: Expo Web Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v3

      - name: Node.js 설치
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: 의존성 설치
        run: npm install

      - name: Expo CLI 설치
        run: npm install -g expo-cli

      - name: 웹 빌드
        run: expo export --platform web

      - name: 정적 파일 배포
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web-build # expo export 후 생성되는 디렉터리
          publish_branch: gh-pages # 배포 대상 브랜치
